export enum BaseTableIdEnum {
    DASHBOARD_TRANSACTIONS_TABLE = "DASHBOARD_TRANSACTIONS_TABLE",
    DASHBOARD_TRANSFERS_TABLE = "DASHBOARD_TRANSFERS_TABLE",
    DASHBOARD_BULK_TRANSFERS_TABLE = "DASHBOARD_BULK_TRANSFERS_TABLE",
    DASHBOARD_BULK_TRANSFER_BATCH_ENTRIES_TABLE = "DASHBOARD_BULK_TRANSFER_BATCH_ENTRIES_TABLE",
    DASHBOARD_SETTINGS_TEAM_TABLE = "DASHBOARD_SETTINGS_TEAM_TABLE",
    DASHBOARD_AUDIT_LOGS_TABLE = "DASHBOARD_AUDIT_LOGS_TABLE",
    DASHBOARD_PENDING_INVITATIONS_TABLE = "DASHBOARD_PENDING_INVITATIONS_TABLE",
    DASHBOARD_DUMMY_TABLE = "DASHBOARD_DUMMY_TABLE",
    DASHBOARD_ALL_LOAN_PRODUCTS_TABLE = "DASHBOARD_ALL_LOAN_PRODUCTS_TABLE",
}
